env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules:
  no-console: 'off'
  no-unused-vars: 0
  space-before-function-paren: 0
  no-undef: 0
  vue/multi-word-component-names: 'off'
